name: Create PR to Main on Release Merge

on:
  pull_request:
    types:
      - closed
    branches:
      - release-*

jobs:
  create-pr-to-main:
    if: github.event.pull_request.merged == true
    name: Create PR to Main
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: ${{ github.event.pull_request.base.ref }}
          title: 'Merge Release: ${{ github.event.pull_request.base.ref }} into Main'
          body: 'This PR merges the release branch `${{ github.event.pull_request.base.ref }}` into `main`.'

  push-image-dockerhub: 
    name: Push Image DockerHub
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    needs: [create-pr-to-main]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ms.dockerfile
          push: true
          tags: vcnafacul/simulado:stable
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max