name: msSimulado
on:
  pull_request: 
    branches: ["develop"]
    types: [opened, synchronize, reopened, closed]

jobs:
  CI:
    if: github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.action == 'reopened')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Iniciando CI
        run: echo "Iniciando CI"
      - uses: actions/setup-node@v1
        with:
          node-version: 20.x
      - name: Install depends
        run: yarn
      - name: Build app MS Simulado
        run: yarn build
  PUSH:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Iniciando PUSH
        run: echo "Iniciando PUSH"
      - uses: actions/setup-node@v1
        with:
          node-version: 20.x
      - name: Install depends
        run: yarn
      - name: Build app vCnafacul
        run: yarn build
      - name: Build Image
        run: docker build -t mssimulado -f ms.dockerfile .
      - name: docker tags
        run: docker tag mssimulado vcnafacul/simulado:latest
      - name: docker login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
      - name: Image Push
        run: docker push vcnafacul/simulado:latest